name: Fres.io
favicon: null
layout_spectrum: 0.83485
typography_spectrum: 0.67062
title: "Amp'd in Swag'd out"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00bbf9'
    - '#008ca6'
    - '#001a33'
    - '#004553'
  brandStrength: 0.6050946323666722
  lightness: 0.8302442298736423
  saturation: 0.22621495719067752
  rhythmicContrast: 0.8226264622062445
purpose: []
