name: fres.io
favicon: null
layout_spectrum: 0.8579747993499041
typography_spectrum: 0.3873811410740018
title: "Amp'd in Swag'd out"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6050946323666722
  lightness: 0.8302442298736423
  saturation: 0.22621495719067752
  rhythmicContrast: 0.8226264622062445
purpose: []
